### ISSUE TITLE
List组件上下那个线颜色不好看

### ISSUE THREAD

**Issue by 651584008** [KuangPF/mpvue-weui#57]
List组件上下那个线颜色不好看，怎么修改不动呢 也不是有类名 也不是border  就是position ，好难改哦

**Comment by KuangPF** [comment]
线的颜色是 `weui-cells` 的伪元素
``` css
.weui-cells:before {
  top: 0;
  border-top: 1rpx solid #d9d9d9;
}
.weui-cells:after {
  bottom: 0;
  border-bottom: 1rpx solid #d9d9d9;
}
```
https://github.com/KuangPF/mpvue-weui/blob/b9d1d8275411565f412524426ede1d56548e762d/static/weui/weui.css#L24
